---
abstract: "interface to Linux's C<NETLINK_ROUTE> netlink\nsocket protocol"
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CChecker: 0
  ExtUtils::H2PM: 0.07
  Module::Build: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Socket-Netlink-Route
provides:
  IO::Socket::Netlink::Route:
    file: lib/IO/Socket/Netlink/Route.pm
    version: 0.05
  Socket::Netlink::Route:
    file: lib/Socket/Netlink/Route.pm
    version: 0.05
requires:
  Exporter: 5.57
  Socket::Netlink: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
